"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

import type { ActivityEvent, PurchaseOrder } from "@/app/lib/types";
import { seedOrders } from "@/app/lib/seed";
import { api } from "@/app/lib/api/client";

interface AppState {
  orders: PurchaseOrder[];
  setOrders: React.Dispatch<React.SetStateAction<PurchaseOrder[]>>;
  activity: ActivityEvent[];
  setActivity: React.Dispatch<React.SetStateAction<ActivityEvent[]>>;
  isLiveConnected: boolean;
  refreshOrders: () => Promise<void>;
}

const AppStateContext = createContext<AppState | null>(null);

const initialActivity: ActivityEvent[] = [
  {
    title: "Validation completed",
    detail: "2 findings generated by catalog and inventory rules",
    time: "10:43 AM",
    type: "system",
  },
  {
    title: "Order extracted",
    detail: "12 fields and 2 line items recognized",
    time: "10:42 AM",
    type: "system",
  },
  {
    title: "Order submitted",
    detail: "Uploaded by Olivia Park through the web portal",
    time: "10:42 AM",
    type: "human",
  },
];

export function AppStateProvider({ children }: { children: ReactNode }) {
  const [orders, setOrders] = useState<PurchaseOrder[]>(seedOrders);
  const [activity, setActivity] = useState<ActivityEvent[]>(initialActivity);
  const [isLiveConnected, setIsLiveConnected] = useState<boolean>(false);

  const refreshOrders = useCallback(async () => {
    try {
      const liveData = await api.orders.list();
      if (Array.isArray(liveData) && liveData.length > 0) {
        setIsLiveConnected(true);
      }
    } catch {
      setIsLiveConnected(false);
    }
  }, []);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void refreshOrders();

    // Connect to real-time SSE stream via api client
    const cleanup = api.connectRealtimeStream(

      (payload) => {
        setIsLiveConnected(true);
        if (payload.event === "order.created" || payload.event === "order.decided" || payload.event === "erp.synced") {
          setActivity((prev) => [
            {
              title: `Event: ${payload.event}`,
              detail: `Order ${String(payload.data?.po_number || "updated")} status: ${String(payload.data?.status || "processed")}`,
              time: "Just now",
              type: "system",
            },
            ...prev,
          ]);
        }
      },
      () => {
        setIsLiveConnected(false);
      },
    );

    return cleanup;
  }, [refreshOrders]);


  const value = useMemo(
    () => ({ orders, setOrders, activity, setActivity, isLiveConnected, refreshOrders }),
    [orders, activity, isLiveConnected, refreshOrders],
  );

  return (
    <AppStateContext.Provider value={value}>
      {children}
    </AppStateContext.Provider>
  );
}

export function useAppState(): AppState {
  const ctx = useContext(AppStateContext);
  if (!ctx) {
    throw new Error("useAppState must be used within an AppStateProvider");
  }
  return ctx;
}
