"use client";

import {
  createContext,
  useContext,
  useMemo,
  useState,
  type ReactNode,
} from "react";

import type { ActivityEvent, PurchaseOrder } from "@/app/lib/types";
import { seedOrders } from "../../data/orders";

interface AppState {
  orders: PurchaseOrder[];
  setOrders: React.Dispatch<React.SetStateAction<PurchaseOrder[]>>;
  activity: ActivityEvent[];
  setActivity: React.Dispatch<React.SetStateAction<ActivityEvent[]>>;
}

const AppStateContext = createContext<AppState | null>(null);

const initialActivity: ActivityEvent[] = [
  {
    title: "Validation completed",
    detail: "2 findings generated by catalog and inventory rules",
    time: "10:43 AM",
    type: "system",
  },
  {
    title: "Order extracted",
    detail: "12 fields and 2 line items recognized",
    time: "10:42 AM",
    type: "system",
  },
  {
    title: "Order submitted",
    detail: "Uploaded by Olivia Park through the web portal",
    time: "10:42 AM",
    type: "human",
  },
];

export function AppStateProvider({ children }: { children: ReactNode }) {
  const [orders, setOrders] = useState(seedOrders);
  const [activity, setActivity] = useState(initialActivity);

  const value = useMemo(
    () => ({ orders, setOrders, activity, setActivity }),
    [orders, activity],
  );

  return (
    <AppStateContext.Provider value={value}>
      {children}
    </AppStateContext.Provider>
  );
}

export function useAppState(): AppState {
  const ctx = useContext(AppStateContext);
  if (!ctx) {
    throw new Error("useAppState must be used within an AppStateProvider");
  }
  return ctx;
}
