"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

import type { ActivityEvent, Decision, FindingCode, OrderStatus, PurchaseOrder } from "@/app/lib/types";
import { FINDING_TITLE } from "@/app/lib/types";
import { seedOrders } from "@/app/lib/seed";
import { api } from "@/app/lib/api/client";

interface AppState {
  orders: PurchaseOrder[];
  setOrders: React.Dispatch<React.SetStateAction<PurchaseOrder[]>>;
  activity: ActivityEvent[];
  setActivity: React.Dispatch<React.SetStateAction<ActivityEvent[]>>;
  isLiveConnected: boolean;
  refreshOrders: () => Promise<void>;
}

const AppStateContext = createContext<AppState | null>(null);

const initialActivity: ActivityEvent[] = [
  {
    title: "Validation completed",
    detail: "2 findings generated by catalog and inventory rules",
    time: "10:43 AM",
    type: "system",
  },
  {
    title: "Order extracted",
    detail: "12 fields and 2 line items recognized",
    time: "10:42 AM",
    type: "system",
  },
  {
    title: "Order submitted",
    detail: "Uploaded by Olivia Park through the web portal",
    time: "10:42 AM",
    type: "human",
  },
];

function mapBackendStatusToFE(backendStatus: string): OrderStatus {
  const s = (backendStatus || "").toLowerCase();
  if (s.includes("ready") || s === "ready_for_approval") return "Ready";
  if (s.includes("block")) return "Blocked";
  if (s.includes("approv")) return "Approved";
  if (s.includes("change") || s === "needs_changes") return "Changes requested";
  if (s.includes("reject")) return "Rejected";
  return "Review required";
}

export function AppStateProvider({ children }: { children: ReactNode }) {
  const [orders, setOrders] = useState<PurchaseOrder[]>(seedOrders);
  const [activity, setActivity] = useState<ActivityEvent[]>(initialActivity);
  const [isLiveConnected, setIsLiveConnected] = useState<boolean>(false);

  const refreshOrders = useCallback(async () => {
    try {
      const liveData = await api.orders.list();
      if (Array.isArray(liveData) && liveData.length > 0) {
        const liveOrders: PurchaseOrder[] = await Promise.all(
          liveData.map(async (sum) => {
            try {
              const detail = await api.orders.get(sum.id);
              const mappedDecisions: Decision[] = (detail.decisions || []).map((d) => ({
                type: d.decision === "approved" ? "APPROVE" : d.decision === "rejected" ? "REJECT" : "REQUEST_CHANGES",
                actor: d.actor,
                note: d.note || "",
                createdAt: d.created_at || new Date().toISOString(),
              }));

              return {
                id: detail.po_number || sum.po_number,
                customer: detail.customer || sum.customer,
                submittedAt: detail.created_at || sum.created_at || new Date().toISOString(),
                sourceFile: detail.source_file || `${sum.po_number}.json`,
                value: Number(detail.total ?? sum.total ?? 0),
                currency: detail.currency || sum.currency || "VND",
                status: mapBackendStatusToFE(detail.status || sum.status),
                findings: (detail.findings || []).map((f) => ({
                  code: (f.code as FindingCode) || "PRICE_MISMATCH",
                  severity: f.severity === "error" ? "Error" : "Warning",
                  title: FINDING_TITLE[f.code as FindingCode] || f.message || "Phát hiện bất thường",
                  detail: f.message || "",
                  evidence: f.evidence || "",
                  sku: f.sku || null,
                })),
                lines: (detail.items || []).map((it) => ({
                  sku: it.sku,
                  product: it.name || it.sku,
                  quantity: it.quantity,
                  available: it.stock_available ?? 100,
                  unitPrice: Number(it.unit_price),
                  catalogPrice: Number(it.catalog_unit_price ?? it.unit_price),
                })),
                owner: "Live API Gateway",
                timeline: (detail.decisions || []).map((d) => ({
                  title: d.decision === "approved" ? "Order approved" : "Decision recorded",
                  detail: d.note || `Decision: ${d.decision} by ${d.actor}`,
                  time: d.created_at || "Just now",
                  type: "human" as const,
                })),
                decisions: mappedDecisions,
              };
            } catch {
              return {
                id: sum.po_number,
                customer: sum.customer,
                submittedAt: sum.created_at || new Date().toISOString(),
                sourceFile: `${sum.po_number}.json`,
                value: Number(sum.total),
                currency: sum.currency || "VND",
                status: mapBackendStatusToFE(sum.status),
                findings: [],
                lines: [],
                owner: "Live API Gateway",
                timeline: [],
                decisions: [],
              };
            }
          }),
        );
        setOrders(liveOrders);
        setIsLiveConnected(true);
      } else {
        setIsLiveConnected(true);
      }
    } catch {
      setIsLiveConnected(false);
    }
  }, []);



  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void refreshOrders();

    // Connect to real-time SSE stream via api client
    const cleanup = api.connectRealtimeStream(

      (payload) => {
        setIsLiveConnected(true);
        if (payload.event === "order.created" || payload.event === "order.decided" || payload.event === "erp.synced") {
          setActivity((prev) => [
            {
              title: `Event: ${payload.event}`,
              detail: `Order ${String(payload.data?.po_number || "updated")} status: ${String(payload.data?.status || "processed")}`,
              time: "Just now",
              type: "system",
            },
            ...prev,
          ]);
        }
      },
      () => {
        setIsLiveConnected(false);
      },
    );

    return cleanup;
  }, [refreshOrders]);


  const value = useMemo(
    () => ({ orders, setOrders, activity, setActivity, isLiveConnected, refreshOrders }),
    [orders, activity, isLiveConnected, refreshOrders],
  );

  return (
    <AppStateContext.Provider value={value}>
      {children}
    </AppStateContext.Provider>
  );
}

export function useAppState(): AppState {
  const ctx = useContext(AppStateContext);
  if (!ctx) {
    throw new Error("useAppState must be used within an AppStateProvider");
  }
  return ctx;
}
